language: python
python:
  - 3.7.6
install:
  - pip install -r requirements.txt
  - pip install --user coverage
  - pip install --user codecov
script:
  - python manage.py test
after_success:
  - codecov